![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide1.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide2.JPG)

In [3]:
x = "i am a data enthusiast"

In [5]:
print x

i am a data enthusiast


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide3.JPG)

In [6]:
#PyPy
#CPython
#IPython
#Jython
#Cython
#Pyston

#mayavi
#VTK wrapper

In [10]:
help(open)

Help on built-in function open in module __builtin__:

open(...)
    open(name[, mode[, buffering]]) -> file object
    
    Open a file using the file() type, returns a file object.  This is the
    preferred way to open a file.  See file.__doc__ for further information.



In [11]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [12]:
help(list.append)

Help on method_descriptor:

append(...)
    L.append(object) -- append object to end



![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide4.JPG)

In [ ]:
# built-in data type
bool- No, True/False - boolean
bytes- No, 
dict{:}, Yes, {'mr A': data scientist, 'Mr B': doctor}
float
int
list[]
set{}
slice :
str 
tuple(,)

In [7]:
# numpy data types
import numpy as np
import pandas as pd

In [8]:
# array
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [9]:
# matrix
np.matrix([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

matrix([[ 1,  2, 23,  4, 56, 78, 32],
        [21, 34, 54, 67, 76, 89, 90]])

In [10]:
# bool_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"bool_")

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [11]:
# int_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [12]:
# int8
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"b")


array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int8)

In [13]:
# int16
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'h')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int16)

In [14]:
# int32
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'i')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int32)

In [15]:
# int64
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'l')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [16]:
# float_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'float_')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [17]:
np.array([[1,2,23,4.,56,78,32],
        [21,34,54,67,76,89,90]])

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [18]:
# float16
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'e')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]], dtype=float16)

In [19]:
# float32
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'f')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]], dtype=float32)

In [20]:
# float64
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'d')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [21]:
# float128
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'g')

array([[ 1.0,  2.0,  23.0,  4.0,  56.0,  78.0,  32.0],
       [ 21.0,  34.0,  54.0,  67.0,  76.0,  89.0,  90.0]], dtype=float128)

In [22]:
# complex_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'complex_')

array([[  1.+0.j,   2.+0.j,  23.+0.j,   4.+0.j,  56.+0.j,  78.+0.j,
         32.+0.j],
       [ 21.+0.j,  34.+0.j,  54.+0.j,  67.+0.j,  76.+0.j,  89.+0.j,
         90.+0.j]])

In [ ]:
# Assignment
# create 1 arrary each by using
# Text data
# Numeric Data (float)
# Integer Data
# Try converting an integer array to float array

In [23]:
# matrix
np.array([["i","am","a","data","geek"],
        ["looking","forward","to","learn","machine","learning"]])

array([['i', 'am', 'a', 'data', 'geek'],
       ['looking', 'forward', 'to', 'learn', 'machine', 'learning']], dtype=object)

In [25]:
# float
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"float_")

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [26]:
# integer
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [27]:
np.NaN

nan

In [36]:
# pandas data type
import pandas as pd

In [37]:
# series
pd.Series([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

0       [1, 2, 23, 4, 56, 78, 32]
1    [21, 34, 54, 67, 76, 89, 90]
dtype: object

In [39]:
# series - one dimensional
pd.Series([[1,2,23,4,56,78,32, 21,34,54,67,76,89,90]])

0    [1, 2, 23, 4, 56, 78, 32, 21, 34, 54, 67, 76, ...
dtype: object

In [37]:
# data frame
df=pd.DataFrame([[1.,2,23,4,56,78,32],
        [21,34,54,67,76,89,90],
             ["i","am","a","data","geek","go","go"],
             [  1.+0.j,   2.+0.j,  23.+0.j,   4.+0.j,  56.+0.j,  78.+0.j,
         32.+0.j]])
df

0       1        2       3        4        5        6
0       1       2       23       4       56       78       32
1      21      34       54      67       76       89       90
2       i      am        a    data     geek       go       go
3  (1+0j)  (2+0j)  (23+0j)  (4+0j)  (56+0j)  (78+0j)  (32+0j)

In [32]:
df.values

array([[1.0, 2, 23, 4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90],
       ['i', 'am', 'a', 'data', 'geek', 'go', 'go'],
       [(1+0j), (2+0j), (23+0j), (4+0j), (56+0j), (78+0j), (32+0j)]], dtype=object)

In [43]:
# Panel
pd.Panel([[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]])

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 1 (major_axis) x 14 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13

In [56]:
df=pd.read_csv("test.csv",sep=" ")
df

0.00632  Unnamed: 1  18.00  Unnamed: 3  Unnamed: 4  2.310  \
NaN 0.02731      NaN         NaN      0         NaN         NaN   7.07   
    0.02729      NaN         NaN      0         NaN         NaN   7.07   
    0.03237      NaN         NaN      0         NaN         NaN   2.18   
    0.06905      NaN         NaN      0         NaN         NaN   2.18   
    0.02985      NaN         NaN      0         NaN         NaN   2.18   
    0.08829      NaN        12.5    NaN         NaN        7.87    NaN   
    0.14455      NaN        12.5    NaN         NaN        7.87    NaN   
    0.21124      NaN        12.5    NaN         NaN        7.87    NaN   
    0.17004      NaN        12.5    NaN         NaN        7.87    NaN   
    0.22489      NaN        12.5    NaN         NaN        7.87    NaN   
    0.11747      NaN        12.5    NaN         NaN        7.87    NaN   
    0.09378      NaN        12.5    NaN         NaN        7.87    NaN   

             Unnamed: 6   0  Unnamed: 8  0.5380  ...    Unnamed: 19  296.0  \
NaN 0.02731         NaN   0         NaN   0.469  ...            NaN  242.0   
    0.02729         NaN   0         NaN   0.469  ...            NaN  242.0   
    0.03237         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.06905         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.02985         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.08829           0 NaN       0.524     NaN  ...            311    NaN   
    0.14455           0 NaN       0.524     NaN  ...            311    NaN   
    0.21124           0 NaN       0.524     NaN  ...            NaN   15.2   
    0.17004           0 NaN       0.524     NaN  ...            311    NaN   
    0.22489           0 NaN       0.524     NaN  ...            311    NaN   
    0.11747           0 NaN       0.524     NaN  ...            311    NaN   
    0.09378           0 NaN       0.524     NaN  ...            311    NaN   

             Unnamed: 21   15.30  396.90  Unnamed: 24  Unnamed: 25   4.98  \
NaN 0.02731          NaN   17.80  396.90          NaN          NaN   9.14   
    0.02729          NaN   17.80  392.83          NaN          NaN   4.03   
    0.03237          NaN   18.70  394.63          NaN          NaN   2.94   
    0.06905          NaN   18.70  396.90          NaN          NaN   5.33   
    0.02985          NaN   18.70  394.12          NaN          NaN   5.21   
    0.08829        15.20  395.60     NaN        12.43          NaN  22.90   
    0.14455        15.20  396.90     NaN        19.15          NaN  27.10   
    0.21124       386.63     NaN   29.93          NaN         16.5    NaN   
    0.17004        15.20  386.71     NaN        17.10          NaN  18.90   
    0.22489        15.20  392.52     NaN        20.45          NaN  15.00   
    0.11747        15.20  396.90     NaN        13.27          NaN  18.90   
    0.09378        15.20  390.50     NaN        15.71          NaN  21.70   

             Unnamed: 27  24.00  
NaN 0.02731          NaN   21.6  
    0.02729          NaN   34.7  
    0.03237          NaN   33.4  
    0.06905          NaN   36.2  
    0.02985          NaN   28.7  
    0.08829          NaN    NaN  
    0.14455          NaN    NaN  
    0.21124          NaN    NaN  
    0.17004          NaN    NaN  
    0.22489          NaN    NaN  
    0.11747          NaN    NaN  
    0.09378          NaN    NaN  

[12 rows x 29 columns]

In [35]:
pd.Panel([[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]])

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 1 (major_axis) x 14 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13

In [60]:
# panel4d
dd = pd.Panel4D([[[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]]],dtype=str)
dd.axes

[Int64Index([0], dtype='int64'),
 Int64Index([0], dtype='int64'),
 Int64Index([0], dtype='int64'),
 Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')]

In [63]:
dd.

<bound method Panel4D.get_values of <class 'pandas.core.panelnd.Panel4D'>
Dimensions: 1 (labels) x 1 (items) x 1 (major_axis) x 14 (minor_axis)
Labels axis: 0 to 0
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13>

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide5.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide6.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide7.JPG)

In [46]:
# strings operation
s = 'data science'
t = "data science"
t == s
u = """data science"""
t == u
s == u

True

In [47]:
# dictionary operation
dict(a=12,b=23)

{'a': 12, 'b': 23}

In [51]:
a = {1: 'Monday',2: 'Tuesday',3: 'wednessday'}
print a

{1: 'Monday', 2: 'Tuesday', 3: 'wednessday'}


In [52]:
b = dict()

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide8.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide9.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide10.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide11.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide11.JPG)

In [3]:
import pandas as pd

import nltk as nl

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide12.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide13.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide14.JPG)

In [54]:
# anonymous function - lambdaa
#f(x) = 3x^2 + 2x - 2
f = lambda x: 3*x**2 + 2*x - 2
f(3)

31

In [55]:
def polynomial(a, b, c):
    return lambda x: a*x**2 + b*x + c

In [57]:
polynomial(3,2,4)

<function __main__.<lambda>>

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide15.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide16.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide17.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide18.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide19.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide20.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide21.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide22.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide23.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide24.JPG)

In [58]:
# modules and import
import os

In [61]:
os.__file__

'/home/ubuntu/anaconda2/lib/python2.7/os.pyc'

In [62]:
os.listdir

<function posix.listdir>

In [63]:
from os import listdir

In [64]:
import nltk.tokenize

In [ ]:
pip install pandas
